name: Build

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: [ubuntu-latest]
    steps:             
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & push Docker image    
        id: build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: user-service
          addLatest: true
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          labels: org.opencontainers.image.source="${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_ACTION_REPOSITORY }}"
